version: '3'

services:
  mongodb:
    image: bitnami/mongodb:4.4.12-debian-10-r4
    ports:
      - 27027:27017
    environment:                 
      - MONGODB_ROOT_PASSWORD=password123      
      - ALLOW_EMPTY_PASSWORD=yes
  data-import:
    build: .
    depends_on: 
      - mongodb 

networks: 
  default: 
    external: 
      name: fast-network 
